### ISSUE TITLE
Add `GenPrism.fields`.

### ISSUE THREAD

**Issue by sellout** [optics-dev/Monocle#363]
I’m unlikely to implement this myself, because I have yet to write a macro successfully.

But, something analogous to `GenIso.fields`.

``` scala
sealed trait Arities
final case class Binary(s: String, i: Int) extends Arities

GenPrism.fields[Arities, Binary] // equiv to Prism[Arities, (String, Int)](…)(…)
```

**Comment by julien-truffaut** [comment]
I suppose we can do:
```scala
GenPrism[Arities, Binary] composePrism GenIso.fields
```

**Comment by sellout** [comment]
That sounds good to me, but I tried
```scala
def GenPrismFields[S, A <: S]: Prism[S, _] = GenPrism[S, A] composeIso GenIso
```
in my project and I end up with a
```
type mismatch;
  found   : quasar.javascript.Js.Str
  required: _$1 where type _$1
       case Str(value) => jscore.literal[Data](Js.Str(value)).right[Data]
                                                     ^
```
each time I use the `apply` on a Prism created that way.

**Comment by julien-truffaut** [comment]
hum it doesn't even compile for me: 

```
Error:(48, 64) abstract type A is unchecked since it is eliminated by erasure
  def GenPrismFields[S, A <: S]: monocle.Prism[S, _] = GenPrism[S, A] composeIso GenIso.fields
                                                               ^
Error:(48, 89) exception during macro expansion: 
scala.ScalaReflectionException: type A is not a class
	at scala.reflect.api.Symbols$SymbolApi$class.asClass(Symbols.scala:275)
	at scala.reflect.internal.Symbols$SymbolContextApiImpl.asClass(Symbols.scala:84)
	at monocle.macros.GenIsoImplW.genIso_fields_impl(GenIso.scala:127)
  def GenPrismFields[S, A <: S]: monocle.Prism[S, _] = GenPrism[S, A] composeIso GenIso.fields
                                                                                        ^
```

**Comment by sellout** [comment]
I got that error at some point, then it went away. I thought it was because I made the type explicit, but I guess that wasn’t it. ¯\\\_(ツ)_/¯

**Comment by japgolly** [comment]
You would need a whitebox macro for this. The reason is that the `_` part of the `Iso[S, _] ` return-type gets replaced with a type determined by the macro, eg `(Int, Int, String, Int)`.

The macro body would be really trivial. It would basically be exactly what you tried above, but in quasiquotes.
```scala
q"GenPrism[S, A] composeIso GenIso.fields"
```

**Comment by julien-truffaut** [comment]
We will review macro for Scala 3
